import type { Metadata } from "next";
import { Inter } from "next/font/google";
import TWProvider from "@/src/providers/TWProvider";
import BiconomyProvider from "@/src/providers/BiconomyProvider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TWProvider>
          <BiconomyProvider>{children}</BiconomyProvider>
        </TWProvider>
      </body>
    </html>
  );
}
